// 導入context套嵌用的客戶端元件
import Providers from './providers'

export const metadata = {
  title: 'React課程',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  )
}
